Header header
float32 ram_used       # [MB]
float32 ram_shared     # [MB]
float32 ram_total      # [MB]
float32 swap_used      # [MB]
float32 swap_total     # [MB]
float32 cpu_temp       # [Celcius]
float32 gpu_load
uint32 gpu_freq        # [kHz]
float32 gpu_temp       # [Celcius]
float32 cpu1_load
uint32 cpu1_freq       # [kHz]
string cpu1_freq_unit
string cpu1_governor
float32 cpu2_load
uint32 cpu2_freq       # [kHz]
string cpu2_freq_unit
string cpu2_governor
float32 cpu3_load
uint32 cpu3_freq       # [kHz]
string cpu3_freq_unit
string cpu3_governor
float32 cpu4_load
uint32 cpu4_freq       # [kHz]
string cpu4_freq_unit
string cpu4_governor
float32 cpu5_load
uint32 cpu5_freq       # [kHz]
string cpu5_freq_unit
string cpu5_governor
float32 cpu6_load
uint32 cpu6_freq       # [kHz]
string cpu6_freq_unit
string cpu6_governor
float32 cpu7_load
uint32 cpu7_freq       # [kHz]
string cpu7_freq_unit
string cpu7_governor
float32 cpu8_load
uint32 cpu8_freq       # [kHz]
string cpu8_freq_unit
string cpu8_governor
